using System;
using System.Collections.Generic;

namespace KC.Models
{
    public class Primary
    {
        public string L1D { get; set; }
        public string L1C { get; set; }
        public string L1E { get; set; }
        public string L1B { get; set; }
        public string L1G { get; set; }
        public string L1F { get; set; }
        public string L1H { get; set; }
        public string L1J { get; set; }
        public string L1I { get; set; }
        public string L1K { get; set; }
    }

    public class Secondary
    {
        public string L2DB { get; set; }
        public string L2DA { get; set; }
        public string L2DG { get; set; }
        public string L2DJ { get; set; }
        public string L2DK { get; set; }
        public string L2DD { get; set; }
        public string L2DE { get; set; }
        public string L2DI { get; set; }
        public string L2DF { get; set; }
        public string L2DH { get; set; }
        public string L2CA { get; set; }
        public string L2CB { get; set; }
        public string L2ED { get; set; }
        public string L2EA { get; set; }
        public string L2EG { get; set; }
        public string L2EE { get; set; }
        public string L2EH { get; set; }
        public string L2EC { get; set; }
        public string L2EF { get; set; }
        public string L2EJ { get; set; }
        public string L2EI { get; set; }
        public string L2EB { get; set; }
        public string L2BA { get; set; }
        public string L2BB { get; set; }
        public string L2BC { get; set; }
        public string L2CC { get; set; }
        public string L2GC { get; set; }
        public string L2GA { get; set; }
        public string L2GG { get; set; }
        public string L2GD { get; set; }
        public string L2GB { get; set; }
        public string L2GE { get; set; }
        public string L2GF { get; set; }
        public string L2GH { get; set; }
        public string L2FD { get; set; }
        public string L2FF { get; set; }
        public string L2FA { get; set; }
        public string L2FC { get; set; }
        public string L2FB { get; set; }
        public string L2FE { get; set; }
        public string L2HA { get; set; }
        public string L2HC { get; set; }
        public string L2JB { get; set; }
        public string L2JC { get; set; }
        public string L2JI { get; set; }
        public string L2JD { get; set; }
        public string L2JA { get; set; }
        public string L2JE { get; set; }
        public string L2JO { get; set; }
        public string L2IH { get; set; }
        public string L2IA { get; set; }
        public string L2IE { get; set; }
        public string L2IB { get; set; }
        public string L2IC { get; set; }
        public string L2IG { get; set; }
        public string L2ID { get; set; }
        public string L2IF { get; set; }
        public string L2IK { get; set; }
        public string L2IJ { get; set; }
        public string L2KB { get; set; }
        public string L2KA { get; set; }
    }

    public class Tertiary
    {
        public string C8410 { get; set; }
        public string C8406 { get; set; }
        public string C8407 { get; set; }
        public string C8402 { get; set; }
        public string C8304 { get; set; }
        public string C6916 { get; set; }
        public string C6915 { get; set; }
        public string C7003 { get; set; }
        public string C7001 { get; set; }
        public string C8303 { get; set; }
        public string C8302 { get; set; }
        public string C7303 { get; set; }
        public string C7301 { get; set; }
        public string C7304 { get; set; }
        public string C7205 { get; set; }
        public string C7306 { get; set; }
        public string C7307 { get; set; }
        public string C7201 { get; set; }
        public string C5501 { get; set; }
        public string C7302 { get; set; }
        public string C7202 { get; set; }
        public string C5102 { get; set; }
        public string C5002 { get; set; }
        public string C5004 { get; set; }
        public string C8411 { get; set; }
        public string C8401 { get; set; }
        public string C7204 { get; set; }
        public string C8409 { get; set; }
        public string C8408 { get; set; }
        public string C8404 { get; set; }
        public string C5101 { get; set; }
        public string C7101 { get; set; }
        public string C8405 { get; set; }
        public string C6917 { get; set; }
        public string C7004 { get; set; }
        public string C8301 { get; set; }
        public string C5003 { get; set; }
        public string C5103 { get; set; }
        public string C8412 { get; set; }
        public string C3806 { get; set; }
        public string C3811 { get; set; }
        public string C3804 { get; set; }
        public string C5801 { get; set; }
        public string C5806 { get; set; }
        public string C8801 { get; set; }
        public string C3816 { get; set; }
        public string C3808 { get; set; }
        public string C3805 { get; set; }
        public string C5808 { get; set; }
        public string C5804 { get; set; }
        public string C5805 { get; set; }
        public string C3802 { get; set; }
        public string C3803 { get; set; }
        public string C3809 { get; set; }
        public string C8802 { get; set; }
        public string C3810 { get; set; }
        public string C5814 { get; set; }
        public string C3813 { get; set; }
        public string C5812 { get; set; }
        public string C3807 { get; set; }
        public string C3817 { get; set; }
        public string C5810 { get; set; }
        public string C5807 { get; set; }
        public string C5811 { get; set; }
        public string C5802 { get; set; }
        public string C5803 { get; set; }
        public string C3812 { get; set; }
        public string C3801 { get; set; }
        public string C6804 { get; set; }
        public string C6802 { get; set; }
        public string C6701 { get; set; }
        public string C6202 { get; set; }
        public string C6201 { get; set; }
        public string C6801 { get; set; }
        public string C6702 { get; set; }
        public string C6803 { get; set; }
        public string C6705 { get; set; }
        public string C6911 { get; set; }
        public string C6703 { get; set; }
        public string C8602 { get; set; }
        public string C8601 { get; set; }
        public string C4401 { get; set; }
        public string C4702 { get; set; }
        public string C4703 { get; set; }
        public string C4705 { get; set; }
        public string C9004 { get; set; }
        public string C4201 { get; set; }
        public string C8701 { get; set; }
        public string C5402 { get; set; }
        public string C5401 { get; set; }
        public string C4002 { get; set; }
        public string C4004 { get; set; }
        public string C5203 { get; set; }
        public string C5204 { get; set; }
        public string C5304 { get; set; }
        public string C8902 { get; set; }
        public string C5405 { get; set; }
        public string C4103 { get; set; }
        public string C4104 { get; set; }
        public string C4102 { get; set; }
        public string C8202 { get; set; }
        public string C4003 { get; set; }
        public string C5305 { get; set; }
        public string C8905 { get; set; }
        public string C5306 { get; set; }
        public string C4005 { get; set; }
        public string C4202 { get; set; }
        public string C4101 { get; set; }
        public string C9001 { get; set; }
        public string C9003 { get; set; }
        public string C5302 { get; set; }
        public string C8903 { get; set; }
        public string C5301 { get; set; }
        public string C5202 { get; set; }
        public string C5201 { get; set; }
        public string C4802 { get; set; }
        public string C5404 { get; set; }
        public string C4805 { get; set; }
        public string C4701 { get; set; }
        public string C8201 { get; set; }
        public string C4804 { get; set; }
        public string C8901 { get; set; }
        public string C5205 { get; set; }
        public string C4001 { get; set; }
        public string C9002 { get; set; }
        public string C5206 { get; set; }
        public string C8904 { get; set; }
        public string C6001 { get; set; }
        public string C5303 { get; set; }
        public string C5702 { get; set; }
        public string C5708 { get; set; }
        public string C5705 { get; set; }
        public string C5706 { get; set; }
        public string C5707 { get; set; }
        public string C5710 { get; set; }
        public string C5709 { get; set; }
        public string C5701 { get; set; }
        public string C5711 { get; set; }
        public string C5703 { get; set; }
        public string C6401 { get; set; }
        public string C6402 { get; set; }
        public string C7502 { get; set; }
        public string C7602 { get; set; }
        public string C7702 { get; set; }
        public string C7703 { get; set; }
        public string C7803 { get; set; }
        public string C7503 { get; set; }
        public string C7501 { get; set; }
        public string C7601 { get; set; }
        public string C7802 { get; set; }
        public string C7510 { get; set; }
        public string C7508 { get; set; }
        public string C7603 { get; set; }
        public string C7801 { get; set; }
        public string C7505 { get; set; }
        public string C7506 { get; set; }
        public string C7401 { get; set; }
        public string C8102 { get; set; }
        public string C8001 { get; set; }
        public string C0501 { get; set; }
        public string C8002 { get; set; }
        public string C0201 { get; set; }
        public string C0301 { get; set; }
        public string C0401 { get; set; }
        public string C0403 { get; set; }
        public string C4602 { get; set; }
        public string C4502 { get; set; }
        public string C4601 { get; set; }
        public string C4504 { get; set; }
        public string C8101 { get; set; }
        public string C4501 { get; set; }
        public string C4605 { get; set; }
        public string C4505 { get; set; }
        public string C0502 { get; set; }
        public string C7901 { get; set; }
        public string C0101 { get; set; }
        public string C0103 { get; set; }
        public string C0102 { get; set; }
        public string C0402 { get; set; }
        public string C0302 { get; set; }
        public string C0303 { get; set; }
        public string C0304 { get; set; }
        public string C0305 { get; set; }
        public string C0902 { get; set; }
        public string C0903 { get; set; }
        public string C0904 { get; set; }
        public string C0901 { get; set; }
        public string C0907 { get; set; }
        public string C0601 { get; set; }
        public string C0602 { get; set; }
        public string C0604 { get; set; }
        public string C1002 { get; set; }
        public string C1001 { get; set; }
        public string C1103 { get; set; }
        public string C1101 { get; set; }
        public string C1102 { get; set; }
        public string C1003 { get; set; }
        public string C0603 { get; set; }
        public string C0607 { get; set; }
        public string C0606 { get; set; }
        public string C1202 { get; set; }
        public string C0702 { get; set; }
        public string C0801 { get; set; }
        public string C0805 { get; set; }
        public string C0705 { get; set; }
        public string C0806 { get; set; }
        public string C0803 { get; set; }
        public string C0701 { get; set; }
        public string C0802 { get; set; }
        public string C0704 { get; set; }
        public string C0703 { get; set; }
        public string C1304 { get; set; }
        public string C1305 { get; set; }
        public string C1303 { get; set; }
        public string C8501 { get; set; }
        public string C8502 { get; set; }
    }

    public class SecondaryByPrimary
    {
        public IList<string> L1D { get; set; }
        public IList<string> L1C { get; set; }
        public IList<string> L1E { get; set; }
        public IList<string> L1B { get; set; }
        public IList<string> L1G { get; set; }
        public IList<string> L1F { get; set; }
        public IList<string> L1H { get; set; }
        public IList<string> L1J { get; set; }
        public IList<string> L1I { get; set; }
        public IList<string> L1K { get; set; }
    }

    public class TertiaryBySecondary
    {
        public IList<string> L2DB { get; set; }
        public IList<string> L2DA { get; set; }
        public IList<string> L2DG { get; set; }
        public IList<string> L2DJ { get; set; }
        public IList<string> L2DK { get; set; }
        public IList<string> L2DD { get; set; }
        public IList<string> L2DE { get; set; }
        public IList<string> L2DI { get; set; }
        public IList<string> L2DF { get; set; }
        public IList<string> L2DH { get; set; }
        public IList<string> L2CA { get; set; }
        public IList<string> L2CB { get; set; }
        public IList<string> L2ED { get; set; }
        public IList<string> L2EA { get; set; }
        public IList<string> L2EG { get; set; }
        public IList<string> L2EE { get; set; }
        public IList<string> L2EH { get; set; }
        public IList<string> L2EC { get; set; }
        public IList<string> L2EF { get; set; }
        public IList<string> L2EJ { get; set; }
        public IList<string> L2EI { get; set; }
        public IList<string> L2EB { get; set; }
        public IList<string> L2BA { get; set; }
        public IList<string> L2BB { get; set; }
        public IList<string> L2BC { get; set; }
        public IList<string> L2CC { get; set; }
        public IList<string> L2GC { get; set; }
        public IList<string> L2GA { get; set; }
        public IList<string> L2GG { get; set; }
        public IList<string> L2GD { get; set; }
        public IList<string> L2GB { get; set; }
        public IList<string> L2GE { get; set; }
        public IList<string> L2GF { get; set; }
        public IList<string> L2GH { get; set; }
        public IList<string> L2FD { get; set; }
        public IList<string> L2FF { get; set; }
        public IList<string> L2FA { get; set; }
        public IList<string> L2FC { get; set; }
        public IList<string> L2FB { get; set; }
        public IList<string> L2FE { get; set; }
        public IList<string> L2HA { get; set; }
        public IList<string> L2HC { get; set; }
        public IList<string> L2JB { get; set; }
        public IList<string> L2JC { get; set; }
        public IList<string> L2JI { get; set; }
        public IList<string> L2JD { get; set; }
        public IList<string> L2JA { get; set; }
        public IList<string> L2JE { get; set; }
        public IList<string> L2JO { get; set; }
        public IList<string> L2IH { get; set; }
        public IList<string> L2IA { get; set; }
        public IList<string> L2IE { get; set; }
        public IList<string> L2IB { get; set; }
        public IList<string> L2IC { get; set; }
        public IList<string> L2IG { get; set; }
        public IList<string> L2ID { get; set; }
        public IList<string> L2IF { get; set; }
        public IList<string> L2IK { get; set; }
        public IList<string> L2IJ { get; set; }
        public IList<string> L2KB { get; set; }
        public IList<string> L2KA { get; set; }
    }

    public class CategoriesDirectory
    {
        public IList<string> categoryids { get; set; }
        public Primary primary { get; set; }
        public Secondary secondary { get; set; }
        public Tertiary tertiary { get; set; }
        public SecondaryByPrimary secondaryByPrimary { get; set; }
        public TertiaryBySecondary tertiaryBySecondary { get; set; }
    }




}
